# Generated by Django 5.0.1 on 2024-01-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=3)),
                ('sname', models.CharField(max_length=225)),
                ('scontact', models.CharField(max_length=15)),
            ],
        ),
    ]
