# Generated by Django 5.0.1 on 2024-01-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('pincode', models.PositiveIntegerField()),
                ('number', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
