# Generated by Django 5.0.1 on 2024-01-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_registereduser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
