# Generated by Django 5.0.1 on 2024-01-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_registereduser_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
