# Generated by Django 5.0.1 on 2024-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_registereduser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
