# Generated by Django 5.0.1 on 2024-02-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_registereduser_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
