# Generated by Django 5.0.1 on 2024-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile_images/'),
        ),
    ]
